export const StrainTypes = {
	GET_STRAIN_START: "GET_STRAIN_START",
	GET_STRAIN_SUCCESS: "GET_STRAIN_SUCCESS",
	GET_STRAIN_FAIL: "GET_STRAIN_FAIL",
	GET_ALL_STRAINS_START: "GET_ALL_STRAINS_START",
	GET_ALL_STRAINS_SUCCESS: "GET_ALL_STRAINS_SUCCESS",
    GET_ALL_STRAINS_FAIL: "GET_ALL_STRAINS_FAIL",
    
};
