export const UserTypes = {
	REGISTER_START: "REGISTER_START",
	REGISTER_SUCCESS: "REGISTER_SUCCESS",
	REGISTER_FAIL: "REGISTER_FAIL",
	LOGIN_START: "LOGIN_START",
	LOGIN_SUCCESS: "LOGIN_SUCCESS",
	LOGIN_FAIL: "LOGIN_FAIL",
	SET_USER_START: "SET_USER_START",
	SET_USER_SUCCESS: "SET_USER_SUCCESS",
	SET_USER_FAIL: "SET_USER_FAIL",	
	LOGOUT_USER: 'USER_LOGGED_OUT'
    
};
